spring.datasource.url=jdbc:mysql://shinkansen.proxy.rlwy.net:10444/railway?useSSL=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=RFwZsPKeGfKyZaaXKGZMEbTYHYcDdJwJ

spring.jpa.hibernate.ddl-auto=update
server.port=${PORT:8082}